### ISSUE TITLE
the worlds stars render in the void and fog is a random colour

### ISSUE THREAD

**Issue by hYdos** [KilnGraphics/Blaze4D#28]
This is most likely due to us not having a working VertexBuffer implementation as all world related things will use one. If sodium is loaded than it will also attempt to use a IndexBuffer. 

I plan to work on this tomorrow. progress may be slowed down by #27

**Comment by hYdos** [comment]
basically fixed minus stars rendering in the void and fog becoming a rainbow

**Comment by burgerguy** [comment]
these were both fixed a while ago
