### ISSUE TITLE
Block outline and F3 crosshair doesn't work

### ISSUE THREAD

**Issue by burgerguy** [KilnGraphics/Blaze4D#41]
I think this is due to how Minecraft processes LINES and LINE_STRIP, but I've implemented the correct index buffers and vulkan type and it still doesn't work. In renderdoc, all of the vertices turn to NAN going from the vertex to the fragment shader.

**Comment by OroArmor** [comment]
isnt this fixed?

**Comment by burgerguy** [comment]
this was fixed a while ago
