### ISSUE TITLE
Make UBOs faster and more dynamic

### ISSUE THREAD

**Issue by burgerguy** [KilnGraphics/Blaze4D#42]
Right now, UBOs don't work with custom values defined in the shader JSON. They're also extremely slow, taking up almost half of the entire frame time to update their descriptor sets and copy them.

**Comment by OroArmor** [comment]
Ubos read themselves from the shader json. I should make unknown values crash for testing

**Comment by OroArmor** [comment]
isnt this also fixed?

**Comment by burgerguy** [comment]
this is mostly fixed, but the title is vague. a new issue should be opened later for the slowness issues caused by them.
