### ISSUE TITLE
Tracking issue: Inconsistent descriptor set list updating

### ISSUE THREAD

**Issue by ramidzkh** [KilnGraphics/Blaze4D#52]
https://github.com/Blaze4D-MC/Rosella/blob/89c273d48b6d78c22df356b67199f54e7552963c/src/main/java/me/hydos/rosella/render/renderer/Renderer.java#L418-L425

Doesn't break/hasn't been reported to break with Intel UHD Graphics 630
Consistently breaks with RX 5700 XT
Inconsistently (rarely) breaks with RTX 3060 and GTX 1660

**Comment by hYdos** [comment]
so thats why it happens

**Comment by hYdos** [comment]
breaks on AMD Vega graphics

**Comment by ramidzkh** [comment]
Breaks on Intel(R) HD Graphics 4000 (IVB GT2) Vulkan API 1.2.0, INTEL (i7-3520M)
