### ISSUE TITLE
macOS compatibility

### ISSUE THREAD

**Issue by Dreamail** [KilnGraphics/Blaze4D#64]
will it can work in macOS? Why it could not work in macOS

**Comment by OroArmor** [comment]
Because MacOS is unbased.

**Comment by IMS212** [comment]
based

**Comment by iMonZ** [comment]
> Because MacOS is unbased.

What do you mean with that?
MacOS can use vulkan as well
MoltenVk

**Comment by hYdos** [comment]
MoltenVK doesnt have Vulkan 1.2 support

**Comment by iMonZ** [comment]
> MoltenVK doesnt have Vulkan 1.2 support

It even has 1.3 support I don’t know what you are talking about.

**Comment by CodingRays** [comment]
While moltenVK allows us to use Vulkan on macos that is not a 0 effort port. There are still additional considerations that need to be taken (for example the portability subset features). It is not impossible to do but combined with the fact that we have more than enough work that still needs to be done on windows/linux and that none of us have the tools to test/debug on macOS it is simply not reasonable for us to support it right now.

**Comment by hYdos** [comment]
> > MoltenVK doesnt have Vulkan 1.2 support
> 
> It even has 1.3 support I don’t know what you are talking about.

My bad then.

**Comment by Dreamail** [comment]
> While moltenVK allows us to use Vulkan on macos that is not a 0 effort port. There are still additional considerations that need to be taken (for example the portability subset features). It is not impossible to do but combined with the fact that we have more than enough work that still needs to be done on windows/linux and that none of us have the tools to test/debug on macOS it is simply not reasonable for us to support it right now.

so it will support macos in the future right?

**Comment by leocth** [comment]
If any team member has a machine with macOS to test on, then maybe

(spoiler alert: there's none)

**Comment by Dreamail** [comment]
> If any team member has a machine with macOS to test on, then maybe
> 
> (spoiler alert: there's none)

OK, I am looking forward to it.

**Comment by Birbe** [comment]
> If any team member has a machine with macOS to test on, then maybe
> 
> (spoiler alert: there's none)

not a team member but I have one
