### ISSUE TITLE
unable to get parchment-1.17.1-2021.10.31.pom from the server

### ISSUE THREAD

**Issue by SpidFightFR** [KilnGraphics/Blaze4D#65]
the url `https://maven.hydos.cf/snapshots/org/parchmentmc/data/parchment-1.17.1/2021.10.31/parchment-1.17.1-2021.10.31.pom`
gives the error: `Error 526: Invalid SSL certificate`.

Thus making us unable to build the mod.

**Comment by CodingRays** [comment]
The current main branch is broken and will likely not receive any updates. We are working on a rewrite.
